### ISSUE TITLE
Exchanging 2 custom assets doesn't work.

### ISSUE THREAD

**Issue by fsodano** [lumenswap/lumenswap.io#44] opened 2022-01-27 01:36 UTC
Hi,

Since you've done a very poor job at trialling my previous issue @amovah , here's take 2, hopefully this time you'll pay attention. I won't bother reporting again and you'll be left with a faulty product.

@amovah The reason ARST is not a valid asset is because your product has a bug that changes the issuer when choosing 2 custom assets.

Steps to reproduce:
1. Go to https://obm.lumenswap.io/swap/
2. Add 2 custom assets
3. Select a custom asset 
![image](https://user-images.githubusercontent.com/844181/151275301-41157e43-13f7-49d1-9ae4-d03e47701858.png)
4. Pay attention, and notice that the issuers are different. TTFF for yUSDC, 5T55 for yXLM
5. Select another custom asset
6. Get a 404 and notice that the form replaces the issuer in the destination URL https://obm.lumenswap.io/swap/yUSDC-GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF/yXLM-GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF

If you don't want to fix it that's fine, but what's the point of open sourcing a product if you don't pay attention to contributions? Very poor experience so far.

**Comment by amovah** [comment] 2022-01-27 10:46
Hi @fsodano 
thank you for your feedback. the problem is fixed now.

previous time you gave us a link, that link was not valid. in this time you told us the exact problem and even more you are giving us how to reproduce the bug. thanks.

**Closed** 2022-01-30 06:51 UTC
